Education/EduApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path("logout", views.logout_view, name="logout"),
    path("login", views.login_view, name="login"),
    path("register", views.register, name="register"),
    
    path('speech_to_text', views.speech_to_text, name='speech_to_text'),
    path('save_transcript', views.save_transcript, name='save_transcript'),
    # path('create_notes/<int:speech_data_id>/', views.create_notes, name='create_notes'),
    path('allNotes', views.subject_based_notes, name='subject_based_notes'),
    path('aiQuiz', views.AI_Quiz, name='AI_Quiz'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('saveScore', views.saveScore, name='saveScore'),

    path('tmp', views.tmp, name="tmp")
]

Education/Education/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('EduApp.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Education/EduApp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass


class SpeechData(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=256)
    chapter = models.CharField(max_length=256)
    text = models.TextField()
    date_recorded = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.subject} - {self.chapter} - {self.date_recorded}'
    

class Notes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=256)
    chapter = models.CharField(max_length=256)
    notes = models.TextField()
    date = models.DateTimeField(auto_now_add=True)


class Quiz(models.Model):
    subject = models.CharField(max_length=256)
    chapter = models.CharField(max_length=256)
    question_text = models.TextField()
    answer_choices = models.TextField()
    correct_answer = models.TextField()

class QuizScorecard(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=256)
    chapter = models.CharField(max_length=256)
    score = models.IntegerField()
    date_recorded = models.DateTimeField(auto_now_add=True)

Education/EduApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core import serializers
import requests
from django.db import IntegrityError
from django.urls import reverse
from .models import *
from datetime import datetime
from openai import OpenAI
from django.db.models import Avg, Count


def index(request):
    return render(request, "index.html")



def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmPassword"]

        if password != confirmation:
            return render(request, "register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "register.html")
    

@login_required
def speech_to_text(request):
    return render(request, 'speech_to_text.html')


@login_required
def save_transcript(request):
    if request.method == 'POST':
        transcript = request.POST.get('transcript')
        subject = request.POST.get('subject')
        chapter = request.POST.get('chapter')
        curr_user = request.user
        SpeechData.objects.create(user=request.user, subject=subject, chapter=chapter, text=transcript)
        data = {
            "subject":subject,
            "chapter":chapter,
            "transcript":transcript,
            "curr_user":curr_user
        }
        print("\n\nnote saved successfully\n\n")
        create_notes(data)
        return redirect('index')
    

def create_notes(data):
    print("in create notes function")
    subject = data["subject"]
    print(f"\nSubject: {subject}\n")
    chapter = data["chapter"]
    print(f"\nSubject: {chapter}\n")
    transcript = data["transcript"]
    print(f"\nSubject: {transcript}\n")
    curr_user = data["curr_user"]
    print(f"\nSubject: {curr_user}\n")

    custom_message = f"Provide some extra information in notes too. Create proper notes with heading. make notes point wise too. The data is: {transcript}"
    API_KEY = "API_KEY"
    client = OpenAI(
        api_key=API_KEY
    )

    response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "user", "content": custom_message}
        ]
    )
    reply = response.choices[0].message.content.strip()
    # reply = transcript
    date = datetime.now()
    notes = reply
    print(reply)

    Notes.objects.create(user=curr_user, subject=subject, chapter=chapter, notes=notes, date=date)
    print("Saved the ai notes")


@login_required
def subject_based_notes(request):
    all_notes = Notes.objects.all()

    available_subjects = []
    available_chapters = {}

    for notes in all_notes:
        if notes.subject not in available_subjects:
            available_subjects.append(notes.subject)
            available_chapters[notes.subject] = []

        if notes.chapter not in available_chapters[notes.subject]:
            available_chapters[notes.subject].append(notes.chapter)

    all_notes_json = serializers.serialize('json', all_notes)

    return render(request, "notes.html", {
        "all_notes_json": all_notes_json,
        "available_subjects": available_subjects,
        "available_chapters": available_chapters
    })


@login_required
def AI_Quiz(request):
    all_quiz = Quiz.objects.all()

    available_subjects = []
    available_chapters = {}

    for quiz in all_quiz:
        if quiz.subject not in available_subjects:
            available_subjects.append(quiz.subject)
            available_chapters[quiz.subject] = []

        if quiz.chapter not in available_chapters[quiz.subject]:
            available_chapters[quiz.subject].append(quiz.chapter)

    all_quiz_json = serializers.serialize('json', all_quiz)

    return render(request, "aiQuiz.html", {
        "all_quiz_json": all_quiz_json,
        "available_subjects": available_subjects,
        "available_chapters": available_chapters
    })


@login_required
def dashboard(request):
    quiz_data = QuizScorecard.objects.all()

    subjects = []
    for quiz in quiz_data:
        if quiz.subject not in subjects:
            subjects.append(quiz.subject)

    subj_chap = {}
    for quiz in quiz_data:
        if quiz.subject not in subj_chap:
            subj_chap[quiz.subject] = [quiz.chapter]
        else:
            subj_chap[quiz.subject].append(quiz.chapter)

    pie_chart_no_of_attempts_per_subject = {}
    for quiz in quiz_data:
        if quiz.subject not in pie_chart_no_of_attempts_per_subject:
            pie_chart_no_of_attempts_per_subject[quiz.subject] = 1
        else:
            pie_chart_no_of_attempts_per_subject[quiz.subject] += 1

    line_chart_per_subject = {}
    for quiz in quiz_data:
        if quiz.subject not in line_chart_per_subject:
            line_chart_per_subject[quiz.subject] = {}
            line_chart_per_subject[quiz.subject][quiz.date_recorded] = quiz.score
        else:
            line_chart_per_subject[quiz.subject][quiz.date_recorded] = quiz.score


    line_chart_per_subject_data = []
    for subject, subject_data in line_chart_per_subject.items():
        line_chart_per_subject_data.append((subject, list(subject_data.items())))

    summary_table_data = []
    for subject, chapters in subj_chap.items():
        for chapter in chapters:
            quizzes = quiz_data.filter(subject=subject, chapter=chapter)
            total_attempts = quizzes.count()
            average_score = sum(quiz.score for quiz in quizzes) / total_attempts if total_attempts > 0 else 0
            summary_table_data.append({
                'subject': subject,
                'chapter': chapter,
                'average_score': average_score,
                'total_attempts': total_attempts,
            })

    return render(request, "dashboard.html", {
        "summary_table_data": summary_table_data,
        "pie_chart_no_of_attempts_per_subject": pie_chart_no_of_attempts_per_subject,
        "line_chart_per_subject_data": line_chart_per_subject_data,
    })

    # quiz_data = QuizScorecard.objects.all()
    # subjects = []
    # for quiz in quiz_data:
    #     if quiz.subject not in subjects:
    #         subjects.append(quiz.subject)
    #
    # quiz_data_json = serializers.serialize('json', quiz_data)
    #
    # # Get average score and total attempts for each subject and chapter
    # subject_data = []
    # for subject in subjects:
    #     chapters = QuizScorecard.objects.filter(subject=subject).values('chapter').distinct()
    #     for chapter in chapters:
    #         avg_score = QuizScorecard.objects.filter(subject=subject, chapter=chapter['chapter']).aggregate(Avg('score'))['score__avg']
    #         total_attempts = QuizScorecard.objects.filter(subject=subject, chapter=chapter['chapter']).aggregate(Count('score'))['score__count']
    #         subject_data.append({
    #             'subject': subject,
    #             'chapter': chapter['chapter'],
    #             'avg_score': avg_score,
    #             'total_attempts': total_attempts
    #         })
    #
    # return render(request, 'dashboard.html', {'quiz_data_json': quiz_data_json, 'subjects': subjects, 'subject_data': subject_data})


@login_required
def saveScore(request):
    if request.method == "POST":
        data = request.POST

        subject = data.get('subject')
        chapter = data.get('chapter')
        score = data.get('score')
        if(subject and chapter):
            QuizScorecard.objects.create(user=request.user, subject=subject, chapter=chapter, score=score)
        return redirect('index')


@login_required
def tmp(request):
    all_quiz = Quiz.objects.all()

    available_subjects = []
    available_chapters = {}

    for quiz in all_quiz:
        if quiz.subject not in available_subjects:
            available_subjects.append(quiz.subject)
            available_chapters[quiz.subject] = []

        if quiz.chapter not in available_chapters[quiz.subject]:
            available_chapters[quiz.subject].append(quiz.chapter)

    all_quiz_json = serializers.serialize('json', all_quiz)

    return render(request, "tmp.html", {
        "all_quiz_json": all_quiz_json,
        "available_subjects": available_subjects,
        "available_chapters": available_chapters
    })
    # all_quiz = Quiz.objects.all()
    #
    # available_subjects = []
    # available_chapters = {}  
    #
    # for quiz in all_quiz:
    #     if quiz.subject not in available_subjects:
    #         available_subjects.append(quiz.subject)
    #         available_chapters[quiz.subject] = []
    #

Education/EduApp/templates/dashboard.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EduApp</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="/static/style.css">
    <style>

        body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }
        main {
            flex: 1;
            overflow: auto;
        }
        .footer-section {
            margin-top: auto;
        }
        .flex-container {
            display: flex;
            justify-content: center;
        }
    </style>
</head>
<body>

  <header>
        <nav class="nav-bar">
            <div class="logo">
                <img class="star" src="/static/img/Logo.png" alt="" style="width:25px;">
                <div style="font-size:25px;"><a href="/" style="font-size:25px;text-decoration:none;">EduApp</a></div>
            </div>
            <ul class="menu-items">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'speech_to_text' %}" style="background-color: transparent;text-decoration:none">Audio</a></li>
                    <li><a href="{% url 'subject_based_notes' %}" style="background-color: transparent;text-decoration:none">Ai Notes</a></li>
                    <li><a href="{% url 'dashboard' %}" style="background-color: transparent;text-decoration:none">Dashboard</a></li>
                {%else%}
                    <li><a href="{% url 'login' %}">Audio</a></li>
                    <li><a href="{% url 'login' %}">Ai Notes</a></li>
                    <li><a href="{% url 'login' %}">Dashboard</a></li>
                {%endif%}
                {% if user.is_authenticated %}
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="text-decoration:none;color:white">
                          {{ request.user }} <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu">
                          <li style="color:black"><a href="{% url 'logout' %}" style="color:black;text-decoration:none;padding-left:20px;">Logout</a></li>
                      </ul>
                    </li>
                {% else %}
                <li><a href="{% url 'login' %}">Login</a></li>
                {% endif %}
<!--                <li><a href="{% url 'logout' %}">{{request.user}}</a></li>-->
            </ul>
        </nav>
    </header>

  <main style="background-color: white;padding-bottom:5%;padding-top:5%">
      <div class="flex-container">
      <div>
        <div style="max-width: fit-content; margin-left: auto;margin-right:auto">
          <div >
            <h1 class="text-center mb-4">Dashboard</h1>

            <!-- Summary Table -->
            <table class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>Subject</th>
                  <th>Chapter</th>
                  <th>Average Score</th>
                  <th>Total Attempts</th>
                </tr>
              </thead>
              <tbody>
                {% for row in summary_table_data %}
                <tr>
                  <td>{{ row.subject }}</td>
                  <td>{{ row.chapter }}</td>
                  <td>{{ row.average_score }}</td>
                  <td>{{ row.total_attempts }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>


            <!-- Pie Chart -->
            <div id="piechart_3d" style="width: 900px; height: 500px;"></div>
            <script>
              google.charts.load('current', {'packages':['corechart']});
              google.charts.setOnLoadCallback(drawChart);

              function drawChart() {

                // Set Data
                const data = google.visualization.arrayToDataTable([
                  ['Subject', 'Attempts'],
                  {% for subject, count in pie_chart_no_of_attempts_per_subject.items %}
                  ['{{ subject }}', {{ count }}],
                  {% endfor %}
                ]);

                // Set Options
                const options = {
                  title:'Quiz Subjects Distribution',
                  is3D:true
                };

                // Draw
                const chart = new google.visualization.PieChart(document.getElementById('piechart_3d'));
                chart.draw(data, options);

              }
              </script>

            <!-- Line Charts -->
            {% for subject, subject_data in line_chart_per_subject_data %}
            <div>
              <h6 style="text-align:center;margin-top:40px;">Scores for {{subject}}</h6>
              <canvas id="lineChart{{ forloop.counter }}" style="background-color:white"></canvas>
            </div>

            <script>
              console.log(`Line Chart for Subject: {{ subject }}`)
              var ctxL = document.getElementById("lineChart{{ forloop.counter }}").getContext('2d');
              var lineChart = new Chart(ctxL, {
                type: 'line',
                data: {
                  labels: [{% for item in subject_data %}"{{ item.0 }}",{% endfor %}],
                  datasets: [{
                    label: 'Score',
                    data: [{% for item in subject_data %}{{ item.1 }},{% endfor %}],
                  }]
                },
                options: {
                  responsive: true,
                  title: {
                    display: true,
                    text: "Line Chart for Subject: {{ subject }}"
                  },
                  scales: {
                    x: {
                      grid: {
                        color: 'black'
                      }
                    },
                    y: {
                      grid: {
                        color: 'black'
                      }
                    }
                  }
                }
              });
            </script>
            {% endfor %}

          </div>
        </div>
      </div>
      </div>
   </main>

    <section class="footer-section">
        <div class="container" style="padding-bottom:5rem;">
            <img src="/static/img/star.png" alt="" class="star star-s5">
            <div class="left-side">
                <div class="title">
                    <h1>stay up-to date</h1>
                    <h2>In all subjects and chapters.</h2>
                </div>
            </div>
            <div class="right-side">
                <p class="txt">
                    Master <span>Every Lecture</span>
                    Where AI transforms<span>audio into knowledge and quizzes</span>
                    into mastery.
                </p>
            </div>
        </div>

        <div class="line"></div>

        <div class="container sides">
            <div class="left-side">
                <div class="logo">
                    <img src="/static/img/Logo.png" class="star" alt="">
                    <div>EduApp</div>
                </div>

                <p class="p">
                    We are based in Mumbai, India.<br>
                    our motto is -Ai in knowledge <br>
                    paves the way to excellence.
                </p>
            </div>
            <div class="right-side">
                <ul class="menu">
                    <li><a href="#">Resources</a></li>
                    <li><a href="#">company</a></li>
                    <li><a href="#">help</a></li>
                    <li><a href="#">client</a></li>
                    <li><a href="#">about</a></li>
                    <li><a href="#">support</a></li>
                    <li><a href="#">blog</a></li>
                    <li><a href="#">services</a></li>
                    <li><a href="#">jobs</a></li>
                    <li><a href="#">docs</a></li>
                    <li><a href="#">news</a></li>
                    <li><a href="#">privacy policy</a></li>
                </ul>
            </div>
        </div>
    </section>

    <footer>
        <div class="container">
            <div class="left-side">
                <p> &copy; copyright 2024 . All rights reserved</p>
            </div>
            <div class="right-side center">
                <p>Term and Conditions</p>
            </div>
        </div>
    </footer>


</body>
</html>

Education/EduApp/templates/speech_to_text.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EduApp</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="/static/style.css">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="nav-bar">
            <div class="logo">
                <img class="star" src="/static/img/Logo.png" alt="" style="width:25px;">
                <div style="font-size:25px;"><a href="/" style="font-size:25px;text-decoration:none;color:white">EduApp</a></div>
            </div>
            <ul class="menu-items">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'speech_to_text' %}" style="color:white;background-color: transparent;text-decoration:none">Audio</a></li>
                    <li><a href="{% url 'subject_based_notes' %}" style="color:white;background-color: transparent;text-decoration:none">Ai Notes</a></li>
                    <li><a href="{% url 'dashboard' %}" style="color:white;background-color: transparent;text-decoration:none">Dashboard</a></li>
                {%else%}
                    <li><a href="{% url 'login' %}">Audio</a></li>
                    <li><a href="{% url 'login' %}">Ai Notes</a></li>
                    <li><a href="{% url 'login' %}">Dashboard</a></li>
                {%endif%}
                {% if user.is_authenticated %}
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="text-decoration:none;color:white">
                          {{ request.user }} <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu">
                          <li style="color:black"><a href="{% url 'logout' %}" style="color:black;text-decoration:none;padding-left:20px;">Logout</a></li>
                      </ul>
                    </li>
                {% else %}
                <li><a href="{% url 'login' %}">Login</a></li>
                {% endif %}
<!--                <li><a href="{% url 'logout' %}">{{request.user}}</a></li>-->
            </ul>
        </nav>
    </header>

    <section class="section-one">
        <div class="container">
            <div class="left-side">
                <div class="title">
                    <h1>Speech to Text
                         <img src="/static/img/star.png" alt="" class="star">
                          <br> Start recording notes.</h1>
                </div>

                <p class="p">
                    <form id="speech-data-form" class="text-center">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_subject" style="color:white">Subject:</label>
                            <input type="text" id="id_subject" name="subject" required>
                        </div>
                        <div class="form-group">
                            <label for="id_chapter" style="color:white">Chapter:</label>
                            <input type="text" id="id_chapter" name="chapter" required>
                        </div>
                    </form>
                    <br>
                    <button id="start-btn" class="custom-btn" style="margin-right:10px">Start</button>
                    <button id="pause-resume-btn" class="custom-btn" style="margin-right:10px">Pause</button>
                    <button id="stop-btn" class="custom-btn" style="margin-right:10px" disabled>Stop</button>

                </p>

            </div>
            <div class="right-side pyramid">
                <p id="transcript" class="text-center my-5" style="color:white;text-align:justify;"></p>
            </div>
        </div>
    </section>


    <section class="footer-section">


        <div class="line"></div>

        <div class="container sides">
            <div class="left-side">
                <div class="logo">
                    <img src="/static/img/Logo.png" class="star" alt="">
                    <div>EduApp</div>
                </div>

                <p class="p">
                    We are based in Mumbai, India.<br>
                    our motto is -Ai in knowledge <br>
                    paves the way to excellence.
                </p>
            </div>
            <div class="right-side">
                <ul class="menu">
                    <li><a href="#">Resources</a></li>
                    <li><a href="#">company</a></li>
                    <li><a href="#">help</a></li>
                    <li><a href="#">client</a></li>
                    <li><a href="#">about</a></li>
                    <li><a href="#">support</a></li>
                    <li><a href="#">blog</a></li>
                    <li><a href="#">services</a></li>
                    <li><a href="#">jobs</a></li>
                    <li><a href="#">docs</a></li>
                    <li><a href="#">news</a></li>
                    <li><a href="#">privacy policy</a></li>
                </ul>
            </div>
        </div>
    </section>

    <footer>
        <div class="container">
            <div class="left-side">
                <p> &copy; copyright 2024 . All rights reserved</p>
            </div>
            <div class="right-side center">
                <p>Term and Conditions</p>
            </div>
        </div>
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script>
        const startBtn = document.getElementById('start-btn');
        const pauseResumeBtn = document.getElementById('pause-resume-btn');
        const stopBtn = document.getElementById('stop-btn');
        const transcript = document.getElementById('transcript');
        const form = document.getElementById('speech-data-form');

        let recognition;
        let isPaused = false;
        let finalTranscript = '';

        if ('webkitSpeechRecognition' in window) {
            recognition = new webkitSpeechRecognition();
            recognition.continuous = true;
            recognition.interimResults = true;
        }

        startBtn.addEventListener('click', () => {
            stopBtn.removeAttribute('disabled');
            recognition.start();
            recognition.onresult = (event) => {
                let interimTranscript = '';
                for (let i = event.resultIndex; i < event.results.length; i++) {
                    if (event.results[i].isFinal) {
                        finalTranscript += event.results[i][0].transcript;
                    } else {
                        interimTranscript += event.results[i][0].transcript;
                    }
                }
                transcript.textContent = finalTranscript + interimTranscript;
            };
        });

        pauseResumeBtn.addEventListener('click', () => {
            if (isPaused) {
                recognition.resume();
                pauseResumeBtn.textContent = "Pause";
            } else {
                recognition.stop();
                pauseResumeBtn.textContent = "Resume";
            }
            isPaused = !isPaused;
        });

        stopBtn.addEventListener('click', () => {
            recognition.stop();
            const subject = form.elements.subject.value;
            const chapter = form.elements.chapter.value;
            console.log(subject)
            console.log(chapter)
            saveTranscript(finalTranscript, subject, chapter);
        });

        function saveTranscript(transcriptText, subject, chapter) {
            $.ajax({
                url: '{% url "save_transcript" %}',
                type: 'POST',
                data: {
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                    'transcript': transcriptText,
                    'subject': subject,
                    'chapter': chapter,
                },
                success: function (response) {
                    console.log('Transcript saved:', response);
                    window.location.href = '{% url "index" %}';
                },
                error: function (error) {
                    console.log(`subject: ${subject}, chapter: ${chapter}`)
                    console.error('Error saving transcript:', error);
                },
            });
        }
    </script>

</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.10.4/gsap.min.js" ></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.10.4/ScrollTrigger.min.js" ></script>
<script src="/static/script.js"></script>
</html>